trigger:
  branches:
    exclude:
    - electron-11.x.y

stages:
# Windows
- template: build/azure-pipelines/win32/continuous-build-win32.yml

# Linux
# - template: build/azure-pipelines/linux/continuous-build-linux.yml

# macOS
# - template: build/azure-pipelines/darwin/continuous-build-darwin.yml
